### ISSUE TITLE
Detected by AutoRuns on Windows 10

### ISSUE THREAD

**Issue by NotoriousRebel** [outflanknl/SharpHide#1]
I compiled this with Visual Studio 2019 and then did

Inside powershell running as administrator.
```.\SharpHide.exe action=create keyvalue="C:\Windows\System32\cmd.exe /c calc.exe"```

I then ran autoruns64 as an administrator and saw it that the entry got detected.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763

![caught](https://user-images.githubusercontent.com/36310667/67165578-d2be4c80-f354-11e9-8c46-91838f3d5a0d.png)

**Comment by NotoriousRebel** [comment]
Ok so it seems after some testing that although it is in autoruns you can't delete it unless you use the sharphide action=delete. Moreover, it seems that depending on if you run the exe as a user or an administrator makes a big difference. If using sharphide as a user it seems to work just fine and is not detected by autoruns and when trying to examine it at regedit is that it pops up with an error. Also, when running as administrator it depending on the action it appears in autoruns but you can't delete it but the action don't seem to trigger when logging back on and off.

**Comment by Cn33liz** [comment]
Did you tried the latest code. I made some changes after i published it. I
tested it and it seems to work fine at my side.

Regards,

Cornelis

Op zo 20 okt. 2019 om 22:45 schreef Matt <notifications@github.com>

**Comment by NotoriousRebel** [comment]
Are those latest changes pushed? I tried this with the most recent commit. Also, is there a benefit of running as an elevated user? Because in the test case just running powershell as an administrator those values in the registry never triggered because I was logging in as a normal user not an administrator.

Also even if autoruns detects it, you can't delete it from autoruns which is nice :) 

This is some awesome stuff!

**Comment by Cn33liz** [comment]
Looks like there was a problem with the CommandLine arguments not being
parsed as they should.
I fixed the code so it should work now.
You're correct about Autoruns, which can detect the hidden registry entries
(you can also read that in the eWhitehats whitepaper).

Regards,

Cornelis

Op ma 21 okt. 2019 om 01:25 schreef Matt <notifications@github.com>:

**Comment by NotoriousRebel** [comment]
As this has been resolved closing!
